export const dummyData = [
    {
      id: 1,
      title: 'Dashboard UI Design',
      status: 'Completed',
      activeTask: '0/8',
      owner: 'Ömer Ekşin',
      date: '8 Nisan 2025',
    },
    {
      id: 2,
      title: 'API Development',
      status: 'In Review',
      activeTask: '5/8',
      owner: 'Mehmet Ali Baskın',
      date: '25 Nisan 2025',
    },
    {
      id: 3,
      title: 'Frontend Refactoring',
      status: 'In Progress',
      activeTask: '3/8',
      owner: 'Onur Eren Taşcı',
      date: '15 Nisan 2025',
    },
    {
      id: 4,
      title: 'Login Page Redesign',
      status: 'Completed',
      activeTask: '0/6',
      owner: 'Zeynep Yılmaz',
      date: '1 Nisan 2025',
    },
    {
      id: 5,
      title: 'User Analytics Module',
      status: 'In Progress',
      activeTask: '2/7',
      owner: 'Ali Demir',
      date: '3 Mayıs 2025',
    },
    {
      id: 6,
      title: 'Notification System',
      status: 'In Review',
      activeTask: '4/5',
      owner: 'Elif Kaya',
      date: '20 Nisan 2025',
    },
    {
      id: 7,
      title: 'Database Optimization',
      status: 'Completed',
      activeTask: '0/4',
      owner: 'Burak Arslan',
      date: '10 Mart 2025',
    },
    {
      id: 8,
      title: 'Payment Integration',
      status: 'In Progress',
      activeTask: '6/10',
      owner: 'Seda Koç',
      date: '28 Nisan 2025',
    },
    {
      id: 9,
      title: 'Unit Testing Suite',
      status: 'In Review',
      activeTask: '1/6',
      owner: 'Caner Yıldız',
      date: '5 Mayıs 2025',
    },
    {
      id: 10,
      title: 'Dark Mode Feature',
      status: 'Completed',
      activeTask: '0/3',
      owner: 'Melis Aydın',
      date: '17 Nisan 2025',
    },
    {
      id: 11,
      title: 'Profile Page Enhancements',
      status: 'In Progress',
      activeTask: '3/5',
      owner: 'Ege Tunç',
      date: '11 Nisan 2025',
    },
    {
      id: 12,
      title: 'Settings Panel Revamp',
      status: 'In Review',
      activeTask: '2/4',
      owner: 'İlayda Gür',
      date: '2 Mayıs 2025',
    },
    {
      id: 13,
      title: 'Email Template Design',
      status: 'Completed',
      activeTask: '0/2',
      owner: 'Emirhan Aksoy',
      date: '12 Mart 2025',
    },
    {
      id: 14,
      title: 'Customer Feedback System',
      status: 'In Progress',
      activeTask: '5/7',
      owner: 'Deniz Çelik',
      date: '29 Nisan 2025',
    },
    {
      id: 15,
      title: 'Security Audit',
      status: 'In Review',
      activeTask: '3/5',
      owner: 'Baran Şahin',
      date: '30 Nisan 2025',
    },
    {
      id: 16,
      title: 'Chatbot Integration',
      status: 'Completed',
      activeTask: '0/6',
      owner: 'Nazlı Korkmaz',
      date: '6 Nisan 2025',
    },
    {
      id: 17,
      title: 'Performance Monitoring Tools',
      status: 'In Progress',
      activeTask: '4/8',
      owner: 'Koray Öztürk',
      date: '4 Mayıs 2025',
    },
    {
      id: 18,
      title: 'Landing Page Creation',
      status: 'Completed',
      activeTask: '0/5',
      owner: 'Büşra Arı',
      date: '18 Mart 2025',
    }
  ];
  